DjangoApp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from blog.views import home_page, AboutView, user_profile, post_create, post_detail, logout_view, login_view, \
    register_view, post_delete, post_update

app_name = 'blog'
urlpatterns = [
    path('', home_page, name="home-page"),
    path('about/', AboutView.as_view(), name="about-page"),
    path('user-post/<str:username>', user_profile, name="user-profile"),
    path('new-post/', post_create, name="new-post"),
    path('post-detail/<int:pk>', post_detail, name="post-detail"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login-page"),
    path('register/', register_view, name="register-page"),
    path('post-update/<int:pk>', post_update, name="post-update"),
    path('post-delete/<int:pk>', post_delete, name="post-delete"),

]

blog/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import CASCADE


class AbstractModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class User(AbstractUser, AbstractModel):
    avatar = models.ImageField(default='images.png')

    @property
    def post_count(self):
        return self.posts.count()


class Post(AbstractModel):
    title = models.CharField(max_length=128)
    content = models.TextField()
    published = models.DateField()
    is_active = models.BooleanField(default=False)
    author = models.ForeignKey("blog.User", CASCADE, "posts")

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from blog.models import Post, User


class PostCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            if str(field) != 'is_active':
                self.fields[field].widget.attrs.update(
                    {'class': 'form-control', 'placeholder': f'Enter the {str(field)}'})

    class Meta:
        model = Post
        fields = ['title', 'content', 'is_active']


class LoginForm(forms.Form):
    username = forms.CharField(max_length=28, widget=forms.TextInput(attrs={"class": "form-control", "id": "username"}))
    password = forms.CharField(max_length=28, widget=forms.PasswordInput(
        attrs={"class": "form-control", "id": "password", "type": "password"}))


class UserRegistrationForm(forms.ModelForm):
    password1 = forms.CharField(max_length=28, widget=forms.TextInput(
        attrs={"id": "password", "type": "password"}))
    password2 = forms.CharField(max_length=28, widget=forms.TextInput(
        attrs={"id": "password", "type": "password"}))
    avatar = forms.FileField()

    def save(self, commit=True):
        user = super().save(commit)
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 == password2:
            user.set_password(password1)
            user.save()
        else:
            raise ValidationError("Passwords must be match")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "password1", "password2", "email", "avatar")


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "content", "is_active")

blog/views.py
import datetime

from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import TemplateView

from blog.forms import PostCreateForm, LoginForm, UserRegistrationForm, PostUpdateForm
from blog.models import Post, User


def home_page(request):
    if request.user.is_authenticated:
        posts = Post.objects.exclude(author=request.user).filter(is_active=True).order_by('published')
    else:
        posts = Post.objects.all().filter(is_active=True).order_by('published')
    size = request.GET.get('size', 4)
    page = request.GET.get('page', 1)
    paginator = Paginator(posts, size)
    page_obj = paginator.page(page)
    return render(request, 'blog/home.html', {'page_obj': page_obj})


class AboutView(TemplateView):
    template_name = 'blog/about.html'


@login_required()
def post_create(request):
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        if form.is_valid():
            post = Post(title=form.cleaned_data['title'], content=form.cleaned_data['content'],
                        is_active=form.cleaned_data['is_active'])
            post.author = request.user
            post.published = datetime.datetime.now().strftime('%Y-%m-%d')
            post.save()
            messages.success(request, 'Post successfully created')
            return redirect(reverse('blog:user-profile', kwargs={'username': request.user.username}))
        else:
            return render(request, 'blog/post_form.html', {'form': form})
    else:
        form = PostCreateForm()
        return render(request, 'blog/post_form.html', {'form': form})


def user_profile(request, username):
    posts = Post.objects.filter(author__username=username)
    user = get_object_or_404(User, username=username)
    first_name = user.first_name
    last_name = user.last_name
    return render(request, 'blog/user_posts.html', {'posts': posts,
                                                    'first_name': first_name,
                                                    'last_name': last_name})


def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


@login_required()
def logout_view(request):
    messages.info(request, f'{request.user.username} User successfulley loged out!')
    logout(request)
    return redirect('blog:home-page')


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(request, username=request.POST.get('username'), password=request.POST.get('password'))
            if user is not None:
                login(request, user)
                messages.success(request, f'{request.user.username} User succesfully loged in')
                return redirect('blog:home-page')
            else:
                messages.warning(request, 'User not found')
                return redirect('blog:login-page')
        else:
            return render(request, 'blog/login.html', {'form': form})
    else:
        form = LoginForm()
        return render(request, 'blog/login.html', {'form': form})


def register_view(request):
    form = UserRegistrationForm()
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'User successfully registered')
            return redirect('blog:login-page')
        else:
            return render(request, 'blog/register.html', {'form': form})
    else:
        return render(request, 'blog/register.html', {'form': form})


@login_required()
def post_update(request, pk: int):
    post = Post.objects.get(pk=pk)
    if request.method == "POST":
        form = PostUpdateForm(data=request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, "post successfully updated")
            return redirect(reverse('blog:post-detail', kwargs={"pk": post.id}))
        else:
            return render(request, "blog/post_update.html", {"form": form})
    else:
        form = PostUpdateForm(instance=post)
        return render(request, "blog/post_update.html", {"form": form})


@login_required()
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        messages.success(request, "post successfully deleted")
        post.delete()
        return redirect(reverse('blog:user-profile', kwargs={"username": request.user.username}))
    else:
        return render(request, "blog/post_confirm_delete.html", {"post": post})

templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% block body %}
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
                <h1>About Page</h1>
                    <div class="container mt-5">
                        <h2>About Us</h2>
                        <p>Welcome to our Django Blog! This blog is dedicated to sharing knowledge, experiences, and thoughts on various topics.</p>

                        <h3>Our Mission</h3>
                        <p>Our mission is to provide valuable and insightful content to our readers. We aim to engage, educate, and entertain through our blog posts.</p>

                        <h3>Meet the Team</h3>
                        <p>We are a passionate team of writers, developers, and enthusiasts who love sharing our expertise with the world.</p>

                        <!-- Add more content about your team, mission, etc. -->

                        <p>Feel free to explore our blog and discover a wide range of articles covering different subjects.</p>
                    </div>

                </div>
                {% include 'blog/sidebar.html' %}
              </div>
            </main>
{% endblock %}

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <title>Django Blog</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blog:home-page' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blog:home-page' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'blog:about-page' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if request.user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'blog:new-post' %}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'blog:user-profile' request.user.username %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'blog:logout' %}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'blog:login-page' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'blog:register-page' %}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
{% block body %}
	
{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/blog/home.html
3{% extends 'blog/base.html' %}
{% load static %}
{% block body %}
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="alert alert-{{ message.tags }}">
                    <h6>Django message</h6>
                </div>
                {% for post in page_obj %}
                    <article class="media content-section">
                        <img class="rounded-circle article-img" src="{{ post.author.avatar.url }}">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2"
                                   href="{% url 'blog:user-profile' post.author.username %}">{{ post.author.first_name }} {{ post.author.last_name }}</a>
                                <small class="text-muted">{{ post.published }}</small>
                            </div>
                            <h5><a class="article-title"
                                   href="{% url 'blog:post-detail' post.pk %}">{{ post.title }}</a></h5>
                        </div>
                    </article>
                {% endfor %}
            </div>
            {% include 'blog/sidebar.html' %}
        </div>
        {% include 'blog/poginator.html' %}
    </main>
{% endblock %}

templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block body %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2>Login</h2>
                <form action="{% url 'blog:login-page' %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
                <p>Don't have an account? <a href="{% url 'blog:register-page' %}">Register</a></p>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
{% endblock %}

templates/blog/poginator.html
<div class="row">
    <div class="col-6">
        {% if page_obj.has_previous %}
            <a href="{% url 'blog:home-page' %}?page={{ page_obj.previous_page_number }}"> < {{ page_obj.previous_page_number }} / </a>
        {% endif %}
        {{ page_obj.number }}
        {% if page_obj.has_next %}
            <a href="{% url 'blog:home-page' %}?page={{ page_obj.next_page_number }}"> / {{ page_obj.next_page_number }} > </a>
        {% endif %}
    </div>
</div>

templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% load static %}
{% block body %}

<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="content-section">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Delete Post</legend>
                        <h2>Are you sure you want to delete the post "{{ post.title }}"</h2>
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                        <a class="btn btn-outline-secondary" href="{% url 'blog:post-detail' post.pk %}">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
        {% include 'blog/sidebar.html' %}
    </div>
</main>
{% endblock %}

templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block body %}
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="alert alert-{{ message.tags }}">
                <h6>Django messages might be shown here</h6>
            </div>
            <article class="media content-section">
                <img class="rounded-circle article-img" src="{{ post.author.avatar.url }}">
                <div class="media-body">
                    <div class="article-metadata">
                        <a class="mr-2" href="{% url 'blog:user-profile' post.author.username %}">{{ post.author.first_name }} {{ post.author.last_name }}</a>
                        <small class="text-muted">{{ post.published }}</small>
                        {% if post.author == request.user %}
                        <div>
                            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:post-update' post.pk %}">Update</a>
                            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:post-delete' post.pk %}">Delete</a>
                        </div>
                        {% endif %}

                    </div>
                    <h2 class="article-title">{{ post.title }}</h2>
                    <p class="article-content">{{ post.content }}</p>
                </div>
            </article>
        </div>
        {% include 'blog/sidebar.html' %}
    </div>
</main>
{% endblock %}

templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block body %}
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
                <div class="content-section">
                        <form method="post" action="{% url 'blog:new-post' %}">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="form-group">
                                <button class="btn btn-outline-info" type="submit">Post</button>
                            </div>
                        </form>
                    </div>
                </div>
                {% include 'blog/sidebar.html' %}
              </div>
            </main>
        
{% endblock %}

templates/blog/post_update.html
{% extends 'blog/base.html' %}
{% block body %}
    <h3>Update post</h3>
    <form method="post">
    <div class="row">
       <div class="col-5">
           {% csrf_token %}
           {{ form.as_p }}
           <button class="btn btn-primary">update</button>
       </div>

    </div>

    </form>

{% endblock %}

templates/blog/register.html
{% extends 'blog/base.html' %}
{% load static %}
{% block body %}
   <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2>Register</h2>
                <form action="#" method="post", enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Register</button>
                </form>
                <p>Already have an account? <a href="{% url 'blog:login-page' %}">Login</a></p>
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/sidebar.html
<div class="col-md-4">
    <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>You can put any information here you'd like.
        <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
        </ul>
        </p>
    </div>

</div>

templates/blog/user_posts.html
{% extends 'blog/base.html' %}
{% load static %}
{% block body %}
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        <h6>{{ message }}</h6>
                    </div>
                {% endfor %}
                <h1 class="mb-3">Posts by {{ first_name }} {{ last_name }}</h1>
                {% for post in posts %}
                    <article class="media content-section">
                        <img class="rounded-circle article-img" src="{{ post.author.avatar.url }}">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="#">{{ first_name }} {{ last_name }}</a>
                                <small class="text-muted">{{ post.published }}</small>
                            </div>
                            <h4><a class="article-title" href="{% url 'blog:post-detail' post.pk %}">{{ post.title }}</a></h4>

                        </div>
                    </article>
                {% endfor %}
            </div>
            {% include 'blog/sidebar.html' %}
        </div>
    </main>
{% endblock %}